#!bin/bash

usuarios () {
clear
source usercodes
if [[ "$1" = "verificar" ]]; then
verif_fun
exit
fi
[[ -z ${VERY} ]] && verificar="\033[1;31m[Off]" || verificar="\033[1;32m[On]"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -e "${cor[3]} MENU DE USUARIOS ${cor[2]}  VPS-BARBA"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -e "${cor[1]}[${cor[7]}01${cor[1]}] \033[0;33m>${cor[6]} CREAR NUEVO USUARIO\033[0m"
echo -e "${cor[1]}[${cor[7]}02${cor[1]}] \033[0;33m>${cor[6]} REMOVER USUARIO\033[0m"
echo -e "${cor[1]}[${cor[7]}03${cor[1]}] \033[0;33m>${cor[6]} BLOQUEAR OU DESBLOQUEAR USUARIO\033[0m"
echo -e "${cor[1]}[${cor[7]}04${cor[1]}] \033[0;33m>${cor[6]} EDITAR USUARIO\033[0m"
echo -e "${cor[1]}[${cor[7]}05${cor[1]}] \033[0;33m>${cor[6]} RENOVAR USUARIO\033[0m"
echo -e "${cor[1]}[${cor[7]}06${cor[1]}] \033[0;33m>${cor[6]} DETALHES DE TODOS USUARIOS\033[0m"
echo -e "${cor[1]}[${cor[7]}07${cor[1]}] \033[0;33m>${cor[6]} MONITORAR USUARIOS CONECTADOS\033[0m"
echo -e "${cor[1]}[${cor[7]}08${cor[1]}] \033[0;33m>${cor[6]} ELIMINAR USUARIOS EXPIRADOS\033[0m"
echo -e "${cor[1]}[${cor[7]}09${cor[1]}] \033[0;33m>${cor[6]} BACKUP USUARIOS\033[0m"
echo -e "${cor[1]}[${cor[7]}10${cor[1]}] \033[0;33m>${cor[6]} BAN_NER SSH\033[0m"
echo -e "${cor[1]}[${cor[7]}11${cor[1]}] \033[0;33m>${cor[6]} VERIFICACOES ${verificar}"; [[ -e Limiter.log ]] 
echo -e "${cor[1]}[${cor[7]}12${cor[1]}] \033[0;33m>${cor[6]} VER LOG DO LIMITER"
echo -e "${cor[1]}[${cor[7]}00${cor[1]}] \033[0;33m>${cor[6]} VOLTAR*"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -ne "\033[1;32m OPCION: \033[1;37m" ; read _selecao
case $_selecao in
0)source menu ;;
1)new_user;;
2)remove_user;;
3)block_user;;
4)edit_user;;
5)renew_user;;
6)detail_user;;
7)monit_user;;
8)rm_vencidos;;
9)backup_fun;;
10)baner_fun;;
11)verif_funx;;
12)
[[ -e "${SCPusr}/Limiter.log" ]] && {
 cat ${SCPusr}/Limiter.log
 }
;;
*)
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
usuarios
exit
;;                                                                                                        esac
}

herramientas () {
clear
source cabecalho
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -e "${cor[2]} ∆ ${cor[3]} MENÚ HERRAMIENTAS"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -e "${cor[1]}[${cor[7]}00${cor[1]}] \033[0;33m>${cor[6]} [VOLVER / SALIR]"
echo -e "${cor[1]}[${cor[7]}01${cor[1]}] \033[0;33m>${cor[6]} CREAR BACKUP"
echo -e "${cor[1]}[${cor[7]}02${cor[1]}] \033[0;33m>${cor[6]} RESTAURAR BACKUP"
echo -e "${cor[1]}[${cor[7]}03${cor[1]}] \033[0;33m>${cor[6]} LIMPIAR CACHE"
echo -e "${cor[1]}[${cor[7]}04${cor[1]}] \033[0;33m>${cor[6]} BAD UDP $_badvpn"
echo -e "${cor[1]}[${cor[7]}05${cor[1]}] \033[0;33m>${cor[6]} TCP SPEED $_tcpspeed"
echo -e "${cor[1]}[${cor[7]}06${cor[1]}] \033[0;33m>${cor[6]} FAILBAN $fail_b"
echo -e "${cor[1]}[${cor[7]}07${cor[1]}] \033[0;33m>${cor[6]} SQUID CACHE $_cachesquid"
echo -e "${cor[1]}[${cor[7]}08${cor[1]}] \033[0;33m>${cor[6]} COMPARTIR ARCHIVO ONLINE"
echo -e "${cor[1]}[${cor[7]}09${cor[1]}] \033[0;33m>${cor[6]} TESTEAR SU VELOCIDAD"
echo -e "${cor[1]}[${cor[7]}10${cor[1]}] \033[0;33m>${cor[6]} INFORMACIÓN VPS"
echo -e "${cor[1]}[${cor[7]}11${cor[1]}] \033[0;33m>${cor[6]} AGREGAR / REMOVER HOST-SQUID"
echo -e "${cor[1]}[${cor[7]}12${cor[1]}] \033[0;33m>${cor[6]} GENERADOR DE PAYLOAD"
echo -e "${cor[1]}[${cor[7]}13${cor[1]}] \033[0;33m>${cor[6]} GESTION DE PUERTAS"
echo -e "${cor[1]}[${cor[7]}14${cor[1]}] \033[0;33m>${cor[6]} ULTRA HOST (SCANNER DE SUBDOMINIOS)"
echo -e "${cor[1]}[${cor[7]}15${cor[1]}] \033[0;33m>${cor[6]} VNC SERVER"
echo -e "${cor[1]}[${cor[7]}16${cor[1]}] \033[0;33m>${cor[6]} BRUTE FORCE PAYLOAD"
echo -e "${cor[1]}[${cor[7]}17${cor[1]}] \033[0;33m>${cor[6]} APLICAR BLOQUEO TORRENT"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -ne "${cor[6]}"
echo -ne "\033[1;32m OPCIÓN:\033[1;37m";read _selecao
case $_selecao in
0)
source menu
exit
;;
1)
source ferramentascodes 1
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
2)
source ferramentascodes 2
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
3)
source ferramentascodes 3
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
4)
source ferramentascodes 4
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
5)
source ferramentascodes 5
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
6)
source ferramentascodes 6
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
ferramentas
exit
;;
7)
source ferramentascodes 7
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
8)
source ferramentascodes 8
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
9)
source ferramentascodes 9
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
10)
source ferramentascodes 10
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
11)
source ferramentascodes 11
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
12)
source ferramentascodes 12
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
13)
source  ports.sh
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
14)
echo -e "barra"
echo -ne "\033[1;33m HOST: \033[1;37m"; read hostcaptura
echo -ne "\033[1;33m LÍMITE DE CAPTURA: \033[1;37m"; read limitecaptura
chmod 777 ./ultrahost
./ultrahost "${hostcaptura}" "${limitecaptura}"
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
15)
source ferramentascodes 13
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
16)
source ferramentascodes 14
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
17)
source ferramentascodes 15
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
source menu
exit
;;
*)
echo -ne "\033[1;31m¡Enter, para volver!${cor[0]}"; read p
herramientas
exit
;;
esac
}




clear
source cabecalho
[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m[ACTIVADO]" || _autorun="\033[1;31m[DESACTIVADO]"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -e "${cor[3]} ∆  BIENVENIDOS"
echo -e "${cor[4]} =================================== ${cor[0]}"
echo -e "${cor[1]}[${cor[7]}00${cor[1]}] \033[0;33m>${cor[6]} [VOLVER / SALIR]"
echo -e "${cor[1]}[${cor[7]}01${cor[1]}] \033[0;33m>${cor[6]} GESTIONAR USUARIOS "
echo -e "${cor[1]}[${cor[7]}02${cor[1]}] \033[0;33m>${cor[6]} HERRAMIENTAS"
echo -e "${cor[1]}[${cor[7]}03${cor[1]}] \033[0;33m>${cor[6]} MENU DE INSTALACION"
echo -e "${cor[1]}[${cor[7]}04${cor[1]}] \033[0;33m>\033[1;32m ACTUALIZAR"
echo -e "${cor[1]}[${cor[7]}05${cor[1]}] \033[0;33m>\033[1;31m DESISTALAR VPS BARBA"
echo -e "${cor[1]}[${cor[7]}06${cor[1]}] \033[0;33m>${cor[6]} CAMBIAR COLORES"
echo -e "${cor[1]}[${cor[7]}07${cor[1]}] \033[0;33m>${cor[6]} CONTROL DE USUARIOS $VERIFICAR_PID"
echo -e "${cor[1]}[${cor[7]}08${cor[1]}] \033[0;33m>${cor[6]} AUTO-INICIO $_autorun"
echo -e "${cor[1]}[${cor[7]}09${cor[1]}] \033[0;33m>${cor[6]} CREDITOS DEL SCRIPT"
echo -e "${cor[4]} ===================================  ${cor[0]}"
echo -ne "\033[1;35m OPCIÓN:\033[1;37m"; read _selecao
case $_selecao in
0)
clear
echo -e "${cor[0]}"
exit
;;
1)
clear
usuarios
exit
;;
2)
clear
herramientas
exit
;;
3)
source menu_inst
exit
;;
4)
fun_atualizar
exit
;;
5)
remover_adm
exit
;;
6)
funcao_cores
source menu
exit
;;
7)
funcao_verificacao > /dev/null 2>&1
source menu
source menu
exit
;;
8)
if [[ -e /etc/bash.bashrc-bakup ]]; then
mv -f /etc/bash.bashrc-bakup /etc/bash.bashrc
cat /etc/bash.bashrc | grep -v "/bin/adm" > /tmp/bash
mv -f /tmp/bash /etc/bash.bashrc
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]} \033[1;32mREMOVED SUCESS!"
echo -e "${cor[1]} =================================== ${cor[0]}"
elif [[ -e /etc/bash.bashrc ]]; then
cat /etc/bash.bashrc|grep -v /bin/adm > /etc/bash.bashrc.2
echo '/bin/adm' >> /etc/bash.bashrc.2
cp /etc/bash.bashrc /etc/bash.bashrc-bakup
mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]} \033[1;32mAUTORUN START SUCESS!"
echo -e "${cor[1]} =================================== ${cor[0]}"
fi
sleep 2s
source menu
exit
;;
9)
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "\033[1;32m   EDITADO POR JORGE BARBA "
echo -e "\033[1;37m   TEAM ADM MEXICO "
echo -e "\033[1;31m   EL CONOCIMIENTO ES LIBRE"
echo -e "${cor[1]} =================================== ${cor[0]}"
sleep 10s
source menu
exit
;;
*)
source menu
;;
esac
